# sources.mk - what native.mk and guest.mk both build: the same files with the
# same defines, so the native reference and the sandboxed core are the same
# program. Included, not run.

ROOT := ..
SAM  := $(ROOT)/extern/OpenSamurai/source
MB   ?= $(or $(MINIBOX_DIR),$(HOME)/chimera/extern/chimera-common-minibox)

# ---- OpenSamurai, upstream: the library its own meson build makes (source/
# meson.build opensamuraiSources), whole. Nothing of it uses SDL: the SDL
# frontend is frontend/, which the core is instead.
SAM_NAMES := asm2c battle battle_math battle_setup battle_tables battleexe_core battleexe_rt catalog cheats dos dosmem \
	dsimage duel exe game duel_tables duelexe_core duelexe_rt lzw melee_core melee_rt meleeexe_core meleeexe_rt \
	egraphic isound mgraphic pit tandy tsound asound opl rsound mpu401 misc rp_core rp_rt shared vga start_core \
	start_rt
SAM_SRCS := $(addprefix $(SAM)/,$(addsuffix .c,$(SAM_NAMES)))
# as OpenSamurai's meson.build: gnu11, a release build (-O2), -Wall
SAM_CFLAGS_COMMON := -std=gnu11 -O2 -I$(SAM)

# ---- Munt's libmt32emu, the Roland MT-32 (OpenSamurai's submodule): the
# library its CMake build makes (mt32emu/CMakeLists.txt libmt32emu_CPP_SOURCES),
# less the resamplers that need libsoxr or libsamplerate and the version
# tagging of a shared object. C++; Munt's own flags are its CMake defaults.
MUNT := $(SAM)/../extern/munt/mt32emu/src
MUNT_NAMES := Analog BReverbModel Display File FileStream LA32FloatWaveGenerator LA32Ramp LA32WaveGenerator \
	MidiStreamParser Part Partial PartialManager Poly ROMInfo Synth Tables TVA TVF TVP sha1/sha1 SampleRateConverter \
	c_interface/c_interface srchelper/srctools/src/FIRResampler srchelper/srctools/src/SincResampler \
	srchelper/srctools/src/IIR2xResampler srchelper/srctools/src/LinearResampler srchelper/srctools/src/ResamplerModel \
	srchelper/InternalResampler
MUNT_SRCS := $(addprefix $(MUNT)/,$(addsuffix .cpp,$(MUNT_NAMES)))
# its config.h, generated by CMake upstream: the core's own (munt-config.h)
MUNT_CONFIG := $(ROOT)/build/munt-config/config.h
$(MUNT_CONFIG): munt-config.h
	@mkdir -p $(dir $@)
	cp munt-config.h $@
MUNT_CXXFLAGS_COMMON := -std=c++11 -O2 -I$(ROOT)/build/munt-config -I$(MUNT)

# ---- the core
CORE_NAMES := samurai-driver game-state coro files sha1 wbx-entry
CORE_HDRS := samurai-driver.h coro.h sha1.h $(MUNT_CONFIG)

# the calls the core answers itself (files.c): the game's directory and its
# saved game
WRAP_FLAGS := -Wl,--wrap=fopen -Wl,--wrap=opendir -Wl,--wrap=readdir -Wl,--wrap=closedir

# the patch series goes onto the submodule before anything of OpenSamurai builds
PATCH_STAMP := $(ROOT)/build/patches.stamp
$(PATCH_STAMP): $(wildcard $(ROOT)/patches/*.patch) apply-patches.sh
	sh apply-patches.sh
	@mkdir -p $(dir $@)
	@touch $@

# Every object depends on the flags it was built with: a change to them
# rebuilds it. (A flag change that rebuilds nothing has bitten these cores: a
# red-zone object two weeks older than the flag that forbade it.)
define flags_stamp
$(shell mkdir -p $(1); printf '%s\n' '$(2)' | cmp -s - $(1)/flags || printf '%s\n' '$(2)' > $(1)/flags)
endef
